### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by jph** [pressednet/lumberg#112]
Hi there. Wondering if this project is still maintained. I'm going to be extending the WHM aspect of this gem for my own use, and if the project's still active I'll take a bit more care (and write tests correctly) for PRs down the track.

Things I'm going to add:

* WHM API 1 support
  * Biggest focus being on package management
* One-click cPanel login link generation

**Comment by boone** [comment]
hi @jph, we are not actively developing lumberg. However, if you want to submit a PR I will be happy to review it.
